-- Auto-generated by votrax_dump_to_vhdl.py
-- Votrax SC01A testbench input vectors
-- DO NOT EDIT - regenerate from votrax_input.txt

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package votrax_tb_vectors is

    -- Event types
    constant EV_RESET      : integer := 0;
    constant EV_CLOCK      : integer := 1;
    constant EV_PHONE      : integer := 2;  -- data(5:0)=phone, data(7:6)=inflection
    constant EV_INFLECTION : integer := 3;  -- data(1:0)=inflection

    type input_event_t is record
        ts_us  : integer;  -- timestamp in microseconds
        event  : integer;  -- event type (EV_*)
        data   : integer;  -- event data
    end record;

    constant N_EVENTS : integer := 77;

    type input_vec_array is array(0 to N_EVENTS-1) of input_event_t;

    constant INPUT_VECTORS : input_vec_array := (
        (ts_us=>         0, event=>0, data=>         0),  -- RESET
        (ts_us=>      2407, event=>3, data=>         2),  -- INFLECTION inflection=2
        (ts_us=>      2407, event=>2, data=>       191),  -- PHONE phone=0x3F inflection=2
        (ts_us=>     57056, event=>2, data=>       191),  -- PHONE phone=0x3F inflection=2
        (ts_us=>    557056, event=>2, data=>       191),  -- PHONE phone=0x3F inflection=2
        (ts_us=>    708881, event=>2, data=>       155),  -- PHONE phone=0x1B inflection=2
        (ts_us=>    791675, event=>1, data=>    782000),  -- CLOCK freq=782000Hz
        (ts_us=>    791675, event=>2, data=>       160),  -- PHONE phone=0x20 inflection=2
        (ts_us=>    974769, event=>2, data=>       139),  -- PHONE phone=0x0B inflection=2
        (ts_us=>   1091396, event=>2, data=>       162),  -- PHONE phone=0x22 inflection=2
        (ts_us=>   1174576, event=>1, data=>    756000),  -- CLOCK freq=756000Hz
        (ts_us=>   1174576, event=>2, data=>       190),  -- PHONE phone=0x3E inflection=2
        (ts_us=>   1357618, event=>2, data=>       190),  -- PHONE phone=0x3E inflection=2
        (ts_us=>   1540988, event=>2, data=>       167),  -- PHONE phone=0x27 inflection=2
        (ts_us=>   1723689, event=>2, data=>       141),  -- PHONE phone=0x0D inflection=2
        (ts_us=>   1806951, event=>2, data=>       159),  -- PHONE phone=0x1F inflection=2
        (ts_us=>   1906861, event=>1, data=>    782000),  -- CLOCK freq=782000Hz
        (ts_us=>   1906861, event=>2, data=>       186),  -- PHONE phone=0x3A inflection=2
        (ts_us=>   2056721, event=>2, data=>       170),  -- PHONE phone=0x2A inflection=2
        (ts_us=>   2140244, event=>1, data=>    756000),  -- CLOCK freq=756000Hz
        (ts_us=>   2140244, event=>2, data=>       190),  -- PHONE phone=0x3E inflection=2
        (ts_us=>   2323415, event=>1, data=>    782000),  -- CLOCK freq=782000Hz
        (ts_us=>   2323415, event=>2, data=>       153),  -- PHONE phone=0x19 inflection=2
        (ts_us=>   2406870, event=>2, data=>       181),  -- PHONE phone=0x35 inflection=2
        (ts_us=>   2523216, event=>1, data=>    756000),  -- CLOCK freq=756000Hz
        (ts_us=>   2523216, event=>2, data=>       180),  -- PHONE phone=0x34 inflection=2
        (ts_us=>   2606696, event=>2, data=>       137),  -- PHONE phone=0x09 inflection=2
        (ts_us=>   2673100, event=>2, data=>       162),  -- PHONE phone=0x22 inflection=2
        (ts_us=>   2756348, event=>2, data=>       141),  -- PHONE phone=0x0D inflection=2
        (ts_us=>   2839610, event=>2, data=>       190),  -- PHONE phone=0x3E inflection=2
        (ts_us=>   2856235, event=>2, data=>       191),  -- PHONE phone=0x3F inflection=2
        (ts_us=>   2872885, event=>2, data=>       191),  -- PHONE phone=0x3F inflection=2
        (ts_us=>   2889532, event=>2, data=>       191),  -- PHONE phone=0x3F inflection=2
        (ts_us=>   3389532, event=>2, data=>       191),  -- PHONE phone=0x3F inflection=2
        (ts_us=>   3406180, event=>2, data=>       191),  -- PHONE phone=0x3F inflection=2
        (ts_us=>   3423242, event=>2, data=>       191),  -- PHONE phone=0x3F inflection=2
        (ts_us=>   3439686, event=>2, data=>       191),  -- PHONE phone=0x3F inflection=2
        (ts_us=>   3456128, event=>2, data=>       191),  -- PHONE phone=0x3F inflection=2
        (ts_us=>   3540128, event=>2, data=>       149),  -- PHONE phone=0x15 inflection=2
        (ts_us=>   3690752, event=>1, data=>    782000),  -- CLOCK freq=782000Hz
        (ts_us=>   3690752, event=>2, data=>       137),  -- PHONE phone=0x09 inflection=2
        (ts_us=>   3757364, event=>2, data=>       169),  -- PHONE phone=0x29 inflection=2
        (ts_us=>   3857276, event=>1, data=>    756000),  -- CLOCK freq=756000Hz
        (ts_us=>   3857276, event=>2, data=>       140),  -- PHONE phone=0x0C inflection=2
        (ts_us=>   3974025, event=>2, data=>       131),  -- PHONE phone=0x03 inflection=2
        (ts_us=>   4023792, event=>2, data=>       136),  -- PHONE phone=0x08 inflection=2
        (ts_us=>   4104744, event=>2, data=>       181),  -- PHONE phone=0x35 inflection=2
        (ts_us=>   4221515, event=>2, data=>       183),  -- PHONE phone=0x37 inflection=2
        (ts_us=>   4321419, event=>2, data=>       158),  -- PHONE phone=0x1E inflection=2
        (ts_us=>   4388026, event=>2, data=>       149),  -- PHONE phone=0x15 inflection=2
        (ts_us=>   4537681, event=>2, data=>       131),  -- PHONE phone=0x03 inflection=2
        (ts_us=>   4587374, event=>2, data=>       159),  -- PHONE phone=0x1F inflection=2
        (ts_us=>   4687293, event=>2, data=>       165),  -- PHONE phone=0x25 inflection=2
        (ts_us=>   4803850, event=>2, data=>       136),  -- PHONE phone=0x08 inflection=2
        (ts_us=>   4887108, event=>1, data=>    782000),  -- CLOCK freq=782000Hz
        (ts_us=>   4887108, event=>2, data=>       139),  -- PHONE phone=0x0B inflection=2
        (ts_us=>   5003930, event=>2, data=>       169),  -- PHONE phone=0x29 inflection=2
        (ts_us=>   5103838, event=>1, data=>    756000),  -- CLOCK freq=756000Hz
        (ts_us=>   5103838, event=>2, data=>       170),  -- PHONE phone=0x2A inflection=2
        (ts_us=>   5187096, event=>2, data=>       190),  -- PHONE phone=0x3E inflection=2
        (ts_us=>   5370262, event=>2, data=>       190),  -- PHONE phone=0x3E inflection=2
        (ts_us=>   5553634, event=>2, data=>       155),  -- PHONE phone=0x1B inflection=2
        (ts_us=>   5636692, event=>1, data=>    782000),  -- CLOCK freq=782000Hz
        (ts_us=>   5636692, event=>2, data=>       149),  -- PHONE phone=0x15 inflection=2
        (ts_us=>   5786553, event=>1, data=>    756000),  -- CLOCK freq=756000Hz
        (ts_us=>   5786553, event=>2, data=>       155),  -- PHONE phone=0x1B inflection=2
        (ts_us=>   5869810, event=>1, data=>    782000),  -- CLOCK freq=782000Hz
        (ts_us=>   5869810, event=>2, data=>       149),  -- PHONE phone=0x15 inflection=2
        (ts_us=>   6019674, event=>1, data=>    756000),  -- CLOCK freq=756000Hz
        (ts_us=>   6019674, event=>2, data=>       155),  -- PHONE phone=0x1B inflection=2
        (ts_us=>   6102933, event=>2, data=>       149),  -- PHONE phone=0x15 inflection=2
        (ts_us=>   6252541, event=>2, data=>       155),  -- PHONE phone=0x1B inflection=2
        (ts_us=>   6336050, event=>2, data=>       149),  -- PHONE phone=0x15 inflection=2
        (ts_us=>   6485922, event=>2, data=>       190),  -- PHONE phone=0x3E inflection=2
        (ts_us=>   6502740, event=>2, data=>       191),  -- PHONE phone=0x3F inflection=2
        (ts_us=>   6519189, event=>2, data=>       191),  -- PHONE phone=0x3F inflection=2
        (ts_us=>   6535843, event=>2, data=>       191)   -- PHONE phone=0x3F inflection=2
    );

end package votrax_tb_vectors;
