-- Auto-generated by votrax_dump_to_vhdl.py
-- Votrax SC01A testbench input vectors
-- DO NOT EDIT - regenerate from votrax_input.txt

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package votrax_tb_vectors is

    -- Event types
    constant EV_RESET      : integer := 0;
    constant EV_CLOCK      : integer := 1;
    constant EV_PHONE      : integer := 2;  -- data(5:0)=phone, data(7:6)=inflection
    constant EV_INFLECTION : integer := 3;  -- data(1:0)=inflection

    type input_event_t is record
        ts_us  : integer;  -- timestamp in microseconds
        event  : integer;  -- event type (EV_*)
        data   : integer;  -- event data
    end record;

    constant N_EVENTS : integer := 246;

    type input_vec_array is array(0 to N_EVENTS-1) of input_event_t;

    constant INPUT_VECTORS : input_vec_array := (
        (ts_us=>         0, event=>0, data=>         0),  -- RESET
        (ts_us=>       120, event=>1, data=>    950000),  -- CLOCK freq=950000Hz
        (ts_us=>       135, event=>3, data=>         3),  -- INFLECTION inflection=3
        (ts_us=>       135, event=>2, data=>       254),  -- PHONE phone=0x3E inflection=3
        (ts_us=>    141544, event=>2, data=>       219),  -- PHONE phone=0x1B inflection=3
        (ts_us=>    198069, event=>2, data=>       192),  -- PHONE phone=0x00 inflection=3
        (ts_us=>    244892, event=>2, data=>       216),  -- PHONE phone=0x18 inflection=3
        (ts_us=>    325669, event=>2, data=>       215),  -- PHONE phone=0x17 inflection=3
        (ts_us=>    467080, event=>2, data=>       237),  -- PHONE phone=0x2D inflection=3
        (ts_us=>    530881, event=>2, data=>       195),  -- PHONE phone=0x03 inflection=3
        (ts_us=>    568003, event=>2, data=>       195),  -- PHONE phone=0x03 inflection=3
        (ts_us=>    605126, event=>2, data=>       195),  -- PHONE phone=0x03 inflection=3
        (ts_us=>    642249, event=>2, data=>       195),  -- PHONE phone=0x03 inflection=3
        (ts_us=>    679371, event=>2, data=>       195),  -- PHONE phone=0x03 inflection=3
        (ts_us=>    716495, event=>2, data=>       213),  -- PHONE phone=0x15 inflection=3
        (ts_us=>    828802, event=>2, data=>       192),  -- PHONE phone=0x00 inflection=3
        (ts_us=>    875625, event=>2, data=>       201),  -- PHONE phone=0x09 inflection=3
        (ts_us=>    920024, event=>2, data=>       233),  -- PHONE phone=0x29 inflection=3
        (ts_us=>   1000802, event=>2, data=>       204),  -- PHONE phone=0x0C inflection=3
        (ts_us=>   1081580, event=>2, data=>       234),  -- PHONE phone=0x2A inflection=3
        (ts_us=>   1138105, event=>2, data=>       250),  -- PHONE phone=0x3A inflection=3
        (ts_us=>   1250412, event=>2, data=>       202),  -- PHONE phone=0x0A inflection=3
        (ts_us=>   1314211, event=>2, data=>       205),  -- PHONE phone=0x0D inflection=3
        (ts_us=>   1378010, event=>2, data=>       222),  -- PHONE phone=0x1E inflection=3
        (ts_us=>   1422409, event=>2, data=>       228),  -- PHONE phone=0x24 inflection=3
        (ts_us=>   1607474, event=>2, data=>       205),  -- PHONE phone=0x0D inflection=3
        (ts_us=>   1671273, event=>2, data=>       255),  -- PHONE phone=0x3F inflection=3
        (ts_us=>   2171273, event=>2, data=>       255),  -- PHONE phone=0x3F inflection=3
        (ts_us=>   2671273, event=>2, data=>       255),  -- PHONE phone=0x3F inflection=3
        (ts_us=>   3171273, event=>2, data=>       245),  -- PHONE phone=0x35 inflection=3
        (ts_us=>   3172410, event=>1, data=>    955500),  -- CLOCK freq=955500Hz
        (ts_us=>   3175373, event=>1, data=>    961000),  -- CLOCK freq=961000Hz
        (ts_us=>   3178223, event=>1, data=>    966500),  -- CLOCK freq=966500Hz
        (ts_us=>   3181186, event=>1, data=>    972000),  -- CLOCK freq=972000Hz
        (ts_us=>   3184036, event=>1, data=>    977500),  -- CLOCK freq=977500Hz
        (ts_us=>   3187000, event=>1, data=>    983000),  -- CLOCK freq=983000Hz
        (ts_us=>   3189963, event=>1, data=>    988500),  -- CLOCK freq=988500Hz
        (ts_us=>   3192813, event=>1, data=>    994000),  -- CLOCK freq=994000Hz
        (ts_us=>   3195776, event=>1, data=>    999500),  -- CLOCK freq=999500Hz
        (ts_us=>   3198626, event=>1, data=>   1005000),  -- CLOCK freq=1005000Hz
        (ts_us=>   3201589, event=>1, data=>   1010500),  -- CLOCK freq=1010500Hz
        (ts_us=>   3204553, event=>1, data=>   1016000),  -- CLOCK freq=1016000Hz
        (ts_us=>   3207402, event=>1, data=>   1021500),  -- CLOCK freq=1021500Hz
        (ts_us=>   3210366, event=>1, data=>   1027000),  -- CLOCK freq=1027000Hz
        (ts_us=>   3213215, event=>1, data=>   1032500),  -- CLOCK freq=1032500Hz
        (ts_us=>   3216179, event=>1, data=>   1038000),  -- CLOCK freq=1038000Hz
        (ts_us=>   3219142, event=>1, data=>   1043500),  -- CLOCK freq=1043500Hz
        (ts_us=>   3221992, event=>1, data=>   1049000),  -- CLOCK freq=1049000Hz
        (ts_us=>   3224955, event=>1, data=>   1054500),  -- CLOCK freq=1054500Hz
        (ts_us=>   3227805, event=>1, data=>   1060000),  -- CLOCK freq=1060000Hz
        (ts_us=>   3230768, event=>1, data=>   1065500),  -- CLOCK freq=1065500Hz
        (ts_us=>   3233732, event=>1, data=>   1071000),  -- CLOCK freq=1071000Hz
        (ts_us=>   3236581, event=>1, data=>   1076500),  -- CLOCK freq=1076500Hz
        (ts_us=>   3239545, event=>1, data=>   1082000),  -- CLOCK freq=1082000Hz
        (ts_us=>   3242394, event=>1, data=>   1087500),  -- CLOCK freq=1087500Hz
        (ts_us=>   3245358, event=>1, data=>   1093000),  -- CLOCK freq=1093000Hz
        (ts_us=>   3248321, event=>1, data=>   1098500),  -- CLOCK freq=1098500Hz
        (ts_us=>   3251171, event=>1, data=>   1104000),  -- CLOCK freq=1104000Hz
        (ts_us=>   3254134, event=>1, data=>   1109500),  -- CLOCK freq=1109500Hz
        (ts_us=>   3256984, event=>1, data=>   1115000),  -- CLOCK freq=1115000Hz
        (ts_us=>   3259947, event=>1, data=>   1120500),  -- CLOCK freq=1120500Hz
        (ts_us=>   3262911, event=>1, data=>   1126000),  -- CLOCK freq=1126000Hz
        (ts_us=>   3265760, event=>1, data=>   1131500),  -- CLOCK freq=1131500Hz
        (ts_us=>   3268724, event=>1, data=>   1137000),  -- CLOCK freq=1137000Hz
        (ts_us=>   3271573, event=>1, data=>   1142500),  -- CLOCK freq=1142500Hz
        (ts_us=>   3274537, event=>1, data=>   1148000),  -- CLOCK freq=1148000Hz
        (ts_us=>   3277500, event=>1, data=>   1153500),  -- CLOCK freq=1153500Hz
        (ts_us=>   3280350, event=>1, data=>   1159000),  -- CLOCK freq=1159000Hz
        (ts_us=>   3283313, event=>1, data=>   1164500),  -- CLOCK freq=1164500Hz
        (ts_us=>   3286163, event=>1, data=>   1170000),  -- CLOCK freq=1170000Hz
        (ts_us=>   3289126, event=>1, data=>   1175500),  -- CLOCK freq=1175500Hz
        (ts_us=>   3292090, event=>1, data=>   1181000),  -- CLOCK freq=1181000Hz
        (ts_us=>   3294940, event=>1, data=>   1186500),  -- CLOCK freq=1186500Hz
        (ts_us=>   3297903, event=>1, data=>   1192000),  -- CLOCK freq=1192000Hz
        (ts_us=>   3300753, event=>1, data=>   1197500),  -- CLOCK freq=1197500Hz
        (ts_us=>   3303716, event=>1, data=>   1203000),  -- CLOCK freq=1203000Hz
        (ts_us=>   3306680, event=>1, data=>   1208500),  -- CLOCK freq=1208500Hz
        (ts_us=>   3309529, event=>1, data=>   1214000),  -- CLOCK freq=1214000Hz
        (ts_us=>   3312493, event=>1, data=>   1219500),  -- CLOCK freq=1219500Hz
        (ts_us=>   3315342, event=>1, data=>   1225000),  -- CLOCK freq=1225000Hz
        (ts_us=>   3318306, event=>1, data=>   1230500),  -- CLOCK freq=1230500Hz
        (ts_us=>   3321269, event=>1, data=>   1236000),  -- CLOCK freq=1236000Hz
        (ts_us=>   3324119, event=>1, data=>   1241500),  -- CLOCK freq=1241500Hz
        (ts_us=>   3327082, event=>1, data=>   1247000),  -- CLOCK freq=1247000Hz
        (ts_us=>   3329932, event=>1, data=>   1252500),  -- CLOCK freq=1252500Hz
        (ts_us=>   3332895, event=>1, data=>   1258000),  -- CLOCK freq=1258000Hz
        (ts_us=>   3335859, event=>1, data=>   1263500),  -- CLOCK freq=1263500Hz
        (ts_us=>   3338708, event=>1, data=>   1269000),  -- CLOCK freq=1269000Hz
        (ts_us=>   3341672, event=>1, data=>   1274500),  -- CLOCK freq=1274500Hz
        (ts_us=>   3344521, event=>1, data=>   1280000),  -- CLOCK freq=1280000Hz
        (ts_us=>   3347485, event=>1, data=>   1285500),  -- CLOCK freq=1285500Hz
        (ts_us=>   3350448, event=>1, data=>   1291000),  -- CLOCK freq=1291000Hz
        (ts_us=>   3353298, event=>1, data=>   1296500),  -- CLOCK freq=1296500Hz
        (ts_us=>   3356261, event=>1, data=>   1302000),  -- CLOCK freq=1302000Hz
        (ts_us=>   3359111, event=>1, data=>   1307500),  -- CLOCK freq=1307500Hz
        (ts_us=>   3362074, event=>1, data=>   1313000),  -- CLOCK freq=1313000Hz
        (ts_us=>   3365038, event=>1, data=>   1318500),  -- CLOCK freq=1318500Hz
        (ts_us=>   3367887, event=>1, data=>   1324000),  -- CLOCK freq=1324000Hz
        (ts_us=>   3370851, event=>1, data=>   1329500),  -- CLOCK freq=1329500Hz
        (ts_us=>   3373700, event=>1, data=>   1335000),  -- CLOCK freq=1335000Hz
        (ts_us=>   3376664, event=>1, data=>   1340500),  -- CLOCK freq=1340500Hz
        (ts_us=>   3379627, event=>1, data=>   1346000),  -- CLOCK freq=1346000Hz
        (ts_us=>   3382477, event=>1, data=>   1351500),  -- CLOCK freq=1351500Hz
        (ts_us=>   3385440, event=>1, data=>   1357000),  -- CLOCK freq=1357000Hz
        (ts_us=>   3388290, event=>1, data=>   1362500),  -- CLOCK freq=1362500Hz
        (ts_us=>   3391253, event=>1, data=>   1368000),  -- CLOCK freq=1368000Hz
        (ts_us=>   3394217, event=>1, data=>   1373500),  -- CLOCK freq=1373500Hz
        (ts_us=>   3397066, event=>1, data=>   1379000),  -- CLOCK freq=1379000Hz
        (ts_us=>   3400030, event=>1, data=>   1384500),  -- CLOCK freq=1384500Hz
        (ts_us=>   3402880, event=>1, data=>   1390000),  -- CLOCK freq=1390000Hz
        (ts_us=>   3405843, event=>1, data=>   1395500),  -- CLOCK freq=1395500Hz
        (ts_us=>   3408807, event=>1, data=>   1401000),  -- CLOCK freq=1401000Hz
        (ts_us=>   3411656, event=>1, data=>   1406500),  -- CLOCK freq=1406500Hz
        (ts_us=>   3414620, event=>1, data=>   1412000),  -- CLOCK freq=1412000Hz
        (ts_us=>   3417469, event=>1, data=>   1417500),  -- CLOCK freq=1417500Hz
        (ts_us=>   3420433, event=>1, data=>   1423000),  -- CLOCK freq=1423000Hz
        (ts_us=>   3423396, event=>1, data=>   1428500),  -- CLOCK freq=1428500Hz
        (ts_us=>   3426246, event=>1, data=>   1434000),  -- CLOCK freq=1434000Hz
        (ts_us=>   3429209, event=>1, data=>   1439500),  -- CLOCK freq=1439500Hz
        (ts_us=>   3432059, event=>1, data=>   1445000),  -- CLOCK freq=1445000Hz
        (ts_us=>   3435022, event=>1, data=>   1450500),  -- CLOCK freq=1450500Hz
        (ts_us=>   3437986, event=>1, data=>   1456000),  -- CLOCK freq=1456000Hz
        (ts_us=>   3440835, event=>1, data=>   1461500),  -- CLOCK freq=1461500Hz
        (ts_us=>   3443799, event=>1, data=>   1467000),  -- CLOCK freq=1467000Hz
        (ts_us=>   3446648, event=>1, data=>   1472500),  -- CLOCK freq=1472500Hz
        (ts_us=>   3446771, event=>1, data=>   1467000),  -- CLOCK freq=1467000Hz
        (ts_us=>   3456460, event=>1, data=>   1461500),  -- CLOCK freq=1461500Hz
        (ts_us=>   3466148, event=>1, data=>   1456000),  -- CLOCK freq=1456000Hz
        (ts_us=>   3475950, event=>1, data=>   1450500),  -- CLOCK freq=1450500Hz
        (ts_us=>   3485639, event=>1, data=>   1445000),  -- CLOCK freq=1445000Hz
        (ts_us=>   3495327, event=>1, data=>   1439500),  -- CLOCK freq=1439500Hz
        (ts_us=>   3505129, event=>1, data=>   1434000),  -- CLOCK freq=1434000Hz
        (ts_us=>   3514818, event=>1, data=>   1428500),  -- CLOCK freq=1428500Hz
        (ts_us=>   3524506, event=>1, data=>   1423000),  -- CLOCK freq=1423000Hz
        (ts_us=>   3534309, event=>1, data=>   1417500),  -- CLOCK freq=1417500Hz
        (ts_us=>   3543997, event=>1, data=>   1412000),  -- CLOCK freq=1412000Hz
        (ts_us=>   3553685, event=>1, data=>   1406500),  -- CLOCK freq=1406500Hz
        (ts_us=>   3563488, event=>1, data=>   1401000),  -- CLOCK freq=1401000Hz
        (ts_us=>   3573176, event=>1, data=>   1395500),  -- CLOCK freq=1395500Hz
        (ts_us=>   3582864, event=>1, data=>   1390000),  -- CLOCK freq=1390000Hz
        (ts_us=>   3592667, event=>1, data=>   1384500),  -- CLOCK freq=1384500Hz
        (ts_us=>   3602355, event=>1, data=>   1379000),  -- CLOCK freq=1379000Hz
        (ts_us=>   3612044, event=>1, data=>   1373500),  -- CLOCK freq=1373500Hz
        (ts_us=>   3621846, event=>1, data=>   1368000),  -- CLOCK freq=1368000Hz
        (ts_us=>   3631534, event=>1, data=>   1362500),  -- CLOCK freq=1362500Hz
        (ts_us=>   3641223, event=>1, data=>   1357000),  -- CLOCK freq=1357000Hz
        (ts_us=>   3651025, event=>1, data=>   1351500),  -- CLOCK freq=1351500Hz
        (ts_us=>   3660713, event=>1, data=>   1346000),  -- CLOCK freq=1346000Hz
        (ts_us=>   3670402, event=>1, data=>   1340500),  -- CLOCK freq=1340500Hz
        (ts_us=>   3680204, event=>1, data=>   1335000),  -- CLOCK freq=1335000Hz
        (ts_us=>   3689893, event=>1, data=>   1329500),  -- CLOCK freq=1329500Hz
        (ts_us=>   3699581, event=>1, data=>   1324000),  -- CLOCK freq=1324000Hz
        (ts_us=>   3709383, event=>1, data=>   1318500),  -- CLOCK freq=1318500Hz
        (ts_us=>   3719072, event=>1, data=>   1313000),  -- CLOCK freq=1313000Hz
        (ts_us=>   3728760, event=>1, data=>   1307500),  -- CLOCK freq=1307500Hz
        (ts_us=>   3738563, event=>1, data=>   1302000),  -- CLOCK freq=1302000Hz
        (ts_us=>   3748251, event=>1, data=>   1296500),  -- CLOCK freq=1296500Hz
        (ts_us=>   3757939, event=>1, data=>   1291000),  -- CLOCK freq=1291000Hz
        (ts_us=>   3767742, event=>1, data=>   1285500),  -- CLOCK freq=1285500Hz
        (ts_us=>   3777430, event=>1, data=>   1280000),  -- CLOCK freq=1280000Hz
        (ts_us=>   3787118, event=>1, data=>   1274500),  -- CLOCK freq=1274500Hz
        (ts_us=>   3796921, event=>1, data=>   1269000),  -- CLOCK freq=1269000Hz
        (ts_us=>   3806609, event=>1, data=>   1263500),  -- CLOCK freq=1263500Hz
        (ts_us=>   3816298, event=>1, data=>   1258000),  -- CLOCK freq=1258000Hz
        (ts_us=>   3826100, event=>1, data=>   1252500),  -- CLOCK freq=1252500Hz
        (ts_us=>   3835788, event=>1, data=>   1247000),  -- CLOCK freq=1247000Hz
        (ts_us=>   3845477, event=>1, data=>   1241500),  -- CLOCK freq=1241500Hz
        (ts_us=>   3855279, event=>1, data=>   1236000),  -- CLOCK freq=1236000Hz
        (ts_us=>   3864967, event=>1, data=>   1230500),  -- CLOCK freq=1230500Hz
        (ts_us=>   3874656, event=>1, data=>   1225000),  -- CLOCK freq=1225000Hz
        (ts_us=>   3884458, event=>1, data=>   1219500),  -- CLOCK freq=1219500Hz
        (ts_us=>   3894147, event=>1, data=>   1214000),  -- CLOCK freq=1214000Hz
        (ts_us=>   3903835, event=>1, data=>   1208500),  -- CLOCK freq=1208500Hz
        (ts_us=>   3913637, event=>1, data=>   1203000),  -- CLOCK freq=1203000Hz
        (ts_us=>   3923326, event=>1, data=>   1197500),  -- CLOCK freq=1197500Hz
        (ts_us=>   3933014, event=>1, data=>   1192000),  -- CLOCK freq=1192000Hz
        (ts_us=>   3942816, event=>1, data=>   1186500),  -- CLOCK freq=1186500Hz
        (ts_us=>   3952505, event=>1, data=>   1181000),  -- CLOCK freq=1181000Hz
        (ts_us=>   3962193, event=>1, data=>   1175500),  -- CLOCK freq=1175500Hz
        (ts_us=>   3971996, event=>1, data=>   1170000),  -- CLOCK freq=1170000Hz
        (ts_us=>   3981684, event=>1, data=>   1164500),  -- CLOCK freq=1164500Hz
        (ts_us=>   3991372, event=>1, data=>   1159000),  -- CLOCK freq=1159000Hz
        (ts_us=>   4001175, event=>1, data=>   1153500),  -- CLOCK freq=1153500Hz
        (ts_us=>   4010863, event=>1, data=>   1148000),  -- CLOCK freq=1148000Hz
        (ts_us=>   4020551, event=>1, data=>   1142500),  -- CLOCK freq=1142500Hz
        (ts_us=>   4030354, event=>1, data=>   1137000),  -- CLOCK freq=1137000Hz
        (ts_us=>   4040042, event=>1, data=>   1131500),  -- CLOCK freq=1131500Hz
        (ts_us=>   4049731, event=>1, data=>   1126000),  -- CLOCK freq=1126000Hz
        (ts_us=>   4059533, event=>1, data=>   1120500),  -- CLOCK freq=1120500Hz
        (ts_us=>   4069221, event=>1, data=>   1115000),  -- CLOCK freq=1115000Hz
        (ts_us=>   4078910, event=>1, data=>   1109500),  -- CLOCK freq=1109500Hz
        (ts_us=>   4088712, event=>1, data=>   1104000),  -- CLOCK freq=1104000Hz
        (ts_us=>   4098401, event=>1, data=>   1098500),  -- CLOCK freq=1098500Hz
        (ts_us=>   4108089, event=>1, data=>   1093000),  -- CLOCK freq=1093000Hz
        (ts_us=>   4117891, event=>1, data=>   1087500),  -- CLOCK freq=1087500Hz
        (ts_us=>   4127580, event=>1, data=>   1082000),  -- CLOCK freq=1082000Hz
        (ts_us=>   4137268, event=>1, data=>   1076500),  -- CLOCK freq=1076500Hz
        (ts_us=>   4147070, event=>1, data=>   1071000),  -- CLOCK freq=1071000Hz
        (ts_us=>   4156759, event=>1, data=>   1065500),  -- CLOCK freq=1065500Hz
        (ts_us=>   4166447, event=>1, data=>   1060000),  -- CLOCK freq=1060000Hz
        (ts_us=>   4176250, event=>1, data=>   1054500),  -- CLOCK freq=1054500Hz
        (ts_us=>   4185938, event=>1, data=>   1049000),  -- CLOCK freq=1049000Hz
        (ts_us=>   4195626, event=>1, data=>   1043500),  -- CLOCK freq=1043500Hz
        (ts_us=>   4205429, event=>1, data=>   1038000),  -- CLOCK freq=1038000Hz
        (ts_us=>   4215117, event=>1, data=>   1032500),  -- CLOCK freq=1032500Hz
        (ts_us=>   4224805, event=>1, data=>   1027000),  -- CLOCK freq=1027000Hz
        (ts_us=>   4234608, event=>1, data=>   1021500),  -- CLOCK freq=1021500Hz
        (ts_us=>   4244296, event=>1, data=>   1016000),  -- CLOCK freq=1016000Hz
        (ts_us=>   4253985, event=>1, data=>   1010500),  -- CLOCK freq=1010500Hz
        (ts_us=>   4263787, event=>1, data=>   1005000),  -- CLOCK freq=1005000Hz
        (ts_us=>   4273475, event=>1, data=>    999500),  -- CLOCK freq=999500Hz
        (ts_us=>   4283164, event=>1, data=>    994000),  -- CLOCK freq=994000Hz
        (ts_us=>   4292966, event=>1, data=>    988500),  -- CLOCK freq=988500Hz
        (ts_us=>   4302654, event=>1, data=>    983000),  -- CLOCK freq=983000Hz
        (ts_us=>   4312343, event=>1, data=>    977500),  -- CLOCK freq=977500Hz
        (ts_us=>   4322145, event=>1, data=>    972000),  -- CLOCK freq=972000Hz
        (ts_us=>   4331834, event=>1, data=>    966500),  -- CLOCK freq=966500Hz
        (ts_us=>   4341522, event=>1, data=>    961000),  -- CLOCK freq=961000Hz
        (ts_us=>   4351324, event=>1, data=>    955500),  -- CLOCK freq=955500Hz
        (ts_us=>   4361013, event=>1, data=>    950000),  -- CLOCK freq=950000Hz
        (ts_us=>   4370701, event=>1, data=>    944500),  -- CLOCK freq=944500Hz
        (ts_us=>   4376056, event=>2, data=>       255),  -- PHONE phone=0x3F inflection=3
        (ts_us=>   4831840, event=>2, data=>       255),  -- PHONE phone=0x3F inflection=3
        (ts_us=>   5331840, event=>2, data=>       255),  -- PHONE phone=0x3F inflection=3
        (ts_us=>   5831840, event=>1, data=>   1038000),  -- CLOCK freq=1038000Hz
        (ts_us=>   5831854, event=>2, data=>       193),  -- PHONE phone=0x01 inflection=3
        (ts_us=>   5883626, event=>3, data=>         0),  -- INFLECTION inflection=0
        (ts_us=>   5883626, event=>2, data=>        44),  -- PHONE phone=0x2C inflection=0
        (ts_us=>   6013084, event=>2, data=>        54),  -- PHONE phone=0x36 inflection=0
        (ts_us=>   6055976, event=>3, data=>         2),  -- INFLECTION inflection=2
        (ts_us=>   6055976, event=>2, data=>       187),  -- PHONE phone=0x3B inflection=2
        (ts_us=>   6185434, event=>3, data=>         3),  -- INFLECTION inflection=3
        (ts_us=>   6185434, event=>2, data=>       253),  -- PHONE phone=0x3D inflection=3
        (ts_us=>   6354847, event=>3, data=>         1),  -- INFLECTION inflection=1
        (ts_us=>   6354847, event=>2, data=>        94),  -- PHONE phone=0x1E inflection=1
        (ts_us=>   6395520, event=>3, data=>         0),  -- INFLECTION inflection=0
        (ts_us=>   6395520, event=>2, data=>        15),  -- PHONE phone=0x0F inflection=0
        (ts_us=>   6447291, event=>2, data=>        39),  -- PHONE phone=0x27 inflection=0
        (ts_us=>   6564371, event=>3, data=>         3),  -- INFLECTION inflection=3
        (ts_us=>   6564371, event=>2, data=>       255),  -- PHONE phone=0x3F inflection=3
        (ts_us=>   6598384, event=>3, data=>         2),  -- INFLECTION inflection=2
        (ts_us=>   6598384, event=>2, data=>       179),  -- PHONE phone=0x33 inflection=2
        (ts_us=>   6727842, event=>3, data=>         3),  -- INFLECTION inflection=3
        (ts_us=>   6727842, event=>2, data=>       249),  -- PHONE phone=0x39 inflection=3
        (ts_us=>   6779613, event=>2, data=>       220),  -- PHONE phone=0x1C inflection=3
        (ts_us=>   6831338, event=>2, data=>       255)   -- PHONE phone=0x3F inflection=3
    );

end package votrax_tb_vectors;
