#!/usr/bin/env python3
"""
rom2vhdl.py - Convert SC01/SC01A ROM binary to VHDL case statement
Usage: python3 rom2vhdl.py <rom.bin> <entity_name>
Example: python3 rom2vhdl.py sc01a.bin sc01a_rom
"""

import sys
import struct

def rom2vhdl(rom_path, entity_name):
    with open(rom_path, 'rb') as f:
        data = f.read()

    # 64 phonemes x 8 bytes = 512 bytes
    assert len(data) >= 512, f"ROM too small: {len(data)} bytes, expected >= 512"

    entries = [None] * 64
    for i in range(64):
        offset = i * 8
        # little-endian 64-bit word
        word = struct.unpack_from('<Q', data, offset)[0]
        phoneme_id = (word >> 56) & 0x3F  # oberstes Byte = Phonem-ID
        entries[phoneme_id] = word

    print(f"""-- {entity_name}.vhd
-- Votrax Phoneme Parameter ROM
-- Auto-generated by rom2vhdl.py
--
-- 64 phonemes x 64-bit entries. Combinatorial (async) read.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity {entity_name} is
    port (
        phoneme : in  std_logic_vector(5 downto 0);
        data    : out std_logic_vector(63 downto 0)
    );
end entity;

architecture rtl of {entity_name} is
begin
    process (phoneme)
        variable i_p : std_logic_vector(7 downto 0);
    begin
        i_p := "00" & phoneme;
        case i_p is""")

    for i, word in enumerate(entries):
        print(f'            when x"{i:02X}" =>')
        print(f'                data <= x"{word:016X}";')

    print("""            when others =>
                data <= (others => '0');
        end case;
    end process;
end architecture;""")


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <rom.bin> <entity_name>", file=sys.stderr)
        sys.exit(1)
    rom2vhdl(sys.argv[1], sys.argv[2])
